//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMNC_TH_LAB5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int StaffId { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> Department { get; set; }
        public string StaffMail { get; set; }
    
        public virtual Department Department1 { get; set; }
    }
}
